### ISSUE TITLE
"String" is not convertible to "String?"

### ISSUE THREAD

**Issue by ghost** [hryk224/PCLBlurEffectAlert#8]
I get an error in my title - "String" is not convertible to "String?" on this line:
                
                let alertController = PCLBlurEffectAlert.Controller(title: "Uh-Oh!", message: error?.localizedDescription, effect: UIBlurEffect, style: .alert)

Would be glad to hear any of your ideas, tried to attach a screenshot here, but GitHub experiences some problems...

**Comment by hryk224** [comment]
Hi @Andriyas123 

Thank you for asking.

>I get an error in my title - "String" is not convertible to "String?" on this line:

There is an error in the argument of `effect`.

Please write as follows.

`let alertController = PCLBlurEffectAlert.Controller(title: "Uh-Oh!", message: error?.localizedDescription, effect: UIBlurEffect(style: .extraLight), style: .alert)`

Also, it can be omitted if `UIBlurEffect (style: .extraLight)` is used.

`let alertController = PCLBlurEffectAlert.Controller(title: "Uh-Oh!", message: error?.localizedDescription, style: .alert)`

**Comment by ghost** [comment]
That helped! Thank you!

One more question - by default I hide status bar using the following code: 

`override var prefersStatusBarHidden: Bool {
        return true
    }`

However, as soon as an alert pops up, black status bar appears. How do I still hide it?

**Comment by hryk224** [comment]
@Andriyas123 
Fixed it! #9
I released [v2.1.1](https://github.com/hryk224/PCLBlurEffectAlert/releases/tag/2.1.1).
Please `$ pod update`.

**Comment by ghost** [comment]
You are the best, thank you!

P.S. One more thing, I am so sorry... It seems that I can't change button text colour, it stays blue by default. In the previous version I was able to change it to white. I use .cancel 

Changing this doesn't help...:

`fileprivate var buttonTextColor: [PCLBlurEffectAlert.ActionStyle : UIColor] = [
            .default: .black,
            .cancel: .black,
            .destructive: .red`

I also wanted it to be bold, so I did this in my VC:

`alertController.configure(buttonFont: [.cancel: UIFont.boldSystemFont(ofSize: 20)])`

But how do I change the colour and why is it blue?...

Thank you, hryk224!

**Comment by hryk224** [comment]
@Andriyas123 

Please write as follows.

```
alertController.configure(buttonTextColor: [.cancel:. black])
```

When changing together font.

```
alertController.configure(buttonFont: [.cancel: UIFont.boldSystemFont(ofSize: 20)],
                          buttonTextColor: [.cancel:. black])
```

If changing `.default` `.cancel` `.destructive `

```
alertController.configure(buttonTextColor: [.default: .black,
                                            .cancel: .black,
                                            .destructive: . red])
```

Please try it!

**Comment by ghost** [comment]
hryk224,

It, indeed, worked like a charm. Thank you!!!
